title: Iftesum Ul Bashri Resume Site
email: iftesum.ul@gmail.com
description: >-  
  Resume and project portfolio for Iftesum Ul Bashri, DevOps & Cloud Platform Engineer.
baseurl: ""
url: "https://iftesumul.github.io" # Change to your GitHub Pages URL
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
